/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "BankATMSystem.h"

bool_t
xdr_STRUCTURE (XDR *xdrs, STRUCTURE *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->AccountID))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Ammount))
		 return FALSE;
	return TRUE;
}
