/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BANKATMSYSTEM_H_RPCGEN
#define _BANKATMSYSTEM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct STRUCTURE {
	int AccountID;
	int Ammount;
};
typedef struct STRUCTURE STRUCTURE;

#define BankATMSystem 0x3EEEEEEE
#define VERSION1 1

#if defined(__STDC__) || defined(__cplusplus)
#define CREATE_AN_ACCOUNT 1
extern  int * create_an_account_1(int *, CLIENT *);
extern  int * create_an_account_1_svc(int *, struct svc_req *);
#define ADD_MONEY_TO_AN_ACCOUNT 2
extern  int * add_money_to_an_account_1(STRUCTURE *, CLIENT *);
extern  int * add_money_to_an_account_1_svc(STRUCTURE *, struct svc_req *);
#define WITHDRAW_MONEY_FROM_AN_ACCOUNT 3
extern  int * withdraw_money_from_an_account_1(STRUCTURE *, CLIENT *);
extern  int * withdraw_money_from_an_account_1_svc(STRUCTURE *, struct svc_req *);
#define INQUIRY 4
extern  int * inquiry_1(int *, CLIENT *);
extern  int * inquiry_1_svc(int *, struct svc_req *);
extern int bankatmsystem_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CREATE_AN_ACCOUNT 1
extern  int * create_an_account_1();
extern  int * create_an_account_1_svc();
#define ADD_MONEY_TO_AN_ACCOUNT 2
extern  int * add_money_to_an_account_1();
extern  int * add_money_to_an_account_1_svc();
#define WITHDRAW_MONEY_FROM_AN_ACCOUNT 3
extern  int * withdraw_money_from_an_account_1();
extern  int * withdraw_money_from_an_account_1_svc();
#define INQUIRY 4
extern  int * inquiry_1();
extern  int * inquiry_1_svc();
extern int bankatmsystem_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_STRUCTURE (XDR *, STRUCTURE*);

#else /* K&R C */
extern bool_t xdr_STRUCTURE ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BANKATMSYSTEM_H_RPCGEN */
